### ISSUE TITLE
Is this supported in Grafana 5.3.2 version ?

### ISSUE THREAD

**Issue by VinayDanda** [gbrian/grafana-echart-panel#3]
I exported a dashboard containing echart panel from grafana 5.2.1 version to 5.3.2 version. And I don't see the panels in 5.3.2. I wonder if the echart panel is supported in 5.3.2. Please comment on what would be the problem.

**Comment by gbrian** [comment]
Hi @VinayDanda,
Currently this is super-beta stage, sorry for that 😅 but should be as AFAIK it's not using any specific functionality and I'm developing using a 5.3.2 version to test.
Can you please open borwser's developers tool and see if there's any specific error message in there? 
Thanks

**Comment by riyu94** [comment]
Hi @gbrian,

Yes, we could see some error messages on the updated version of grafana 5.3.2, it is not loading the Options preview.
Below is the error:
**Failed to load resource: the server responded with a status of 503 (Service Unavailable)
send @ jquery.js:9600**

Let me know, if you can make it work, since we will be using these charts in our future dashboards soon. Also, the export to csv option will be needed soon :)
Thank you.

**Comment by gbrian** [comment]
@riyu94 let me see what I can do ;) thanks for your patience. Many things coming in this year!

**Comment by KrishnaPG** [comment]
This could be a great asset for grafana. The in-built charts of Grafana have limitations on what can be done (e.g. can't have a simple bar chart with additional line series on top of it). 

Looking forward for the new version. Great work.

**Comment by riyu94** [comment]
@gbrian Hie, any update for echarts for new versions of grafana, We have built lots of charts using this plugin. Need to deploy sooner. Also, any update on the excel export option, will be really needed. Since the users need the data in excel.

**Comment by gbrian** [comment]
@riyu94 is fine to continue with https://github.com/gbrian/grafana-echart-panel/issues/2 ? If the new version causes problems I'll add the export to the master. BTW super curious on what have you done, will be great if you can share some screenshot when possible and if you can, ofc! Please reopen if needed
